name: 'eazybump'
description: 'Bump package.json with ease for your npm package.'
branding:
  color: 'green'
  icon: 'arrow-up-circle'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'